In [1]:
from pandas_datareader import DataReader
from datetime import datetime
import numpy as np
import pandas as pd
from pandas import read_csv
from pandas import datetime
from matplotlib import pyplot
from sklearn.preprocessing import StandardScaler

FB = DataReader('FB',  'yahoo', datetime(2019,1,1), datetime(2019,12,31));
FB.head()
print(FB.ix[:4,0:6])
FB.ix[:,'Close'].values

                  High         Low        Open       Close    Volume  \
Date                                                                   
2019-01-02  137.509995  128.559998  128.990005  135.679993  28146200   
2019-01-03  137.169998  131.119995  134.690002  131.740005  22717900   
2019-01-04  138.000000  133.750000  134.009995  137.949997  29002100   
2019-01-07  138.869995  135.910004  137.559998  138.050003  20089300   

             Adj Close  
Date                    
2019-01-02  135.679993  
2019-01-03  131.740005  
2019-01-04  137.949997  
2019-01-07  138.050003  


C:\Users\avala\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if sys.path[0] == '':
C:\Users\avala\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  del sys.path[0]


array([135.67999268, 131.74000549, 137.94999695, 138.05000305,
       142.52999878, 144.22999573, 144.19999695, 143.80000305,
       145.38999939, 148.94999695, 147.53999329, 148.30000305,
       150.03999329, 147.57000732, 144.30000305, 145.83000183,
       149.00999451, 147.47000122, 144.19000244, 150.41999817,
       166.69000244, 165.71000671, 169.25      , 171.16000366,
       170.49000549, 166.38000488, 167.33000183, 165.78999329,
       165.03999329, 164.07000732, 163.94999695, 162.5       ,
       162.28999329, 162.55999756, 160.03999329, 161.88999939,
       164.61999512, 164.13000488, 162.80999756, 161.44999695,
       162.27999878, 167.36999512, 171.25999451, 172.50999451,
       169.13000488, 169.6000061 , 172.07000732, 171.91999817,
       173.36999512, 170.16999817, 165.97999573, 160.47000122,
       161.57000732, 165.44000244, 166.08000183, 164.33999634,
       166.28999329, 167.67999268, 165.86999512, 165.55000305,
       166.69000244, 168.69999695, 174.19999695, 173.53

### PCA

In [2]:
def getPCA():
    result = []
    data = FB
    data=FB.dropna()
    X = data.ix[:4,0:6].values
    y = data.ix[:,'Close'].values
    X_std = StandardScaler().fit_transform(X)
    mean_vec = np.mean(X_std, axis=0)
    cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
    cov_mat = np.cov(X_std.T)
    eig_vals, eig_vecs = np.linalg.eig(cov_mat)
    cor_mat2 = np.corrcoef(X.T)
    eig_vals, eig_vecs = np.linalg.eig(cor_mat2)
    eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]
    eig_pairs.sort()
    eig_pairs.reverse()
    print(eig_vecs)
    for i in eig_pairs:
        result.append(i[0])
    return result
getPCA()

C:\Users\avala\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """
C:\Users\avala\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


[[ 0.50044344  0.7715153   0.3887586   0.05645585  0.0363988   0.25517256]
 [ 0.48144448 -0.06282999 -0.46997121 -0.17280906 -0.19549745 -0.69705911]
 [ 0.37853035  0.0187844  -0.4585593  -0.45445443  0.17901378  0.63189102]
 [ 0.40504164 -0.33769034  0.08459646  0.44185377 -0.65868898  0.02014643]
 [-0.2153251   0.41520376 -0.63514097  0.60823633  0.04344679  0.22112788]
 [ 0.40504164 -0.33769034  0.08459646  0.44185377  0.70189112  0.02014643]]


[3.7984683726400967,
 1.919801088227163,
 0.28173053913273993,
 6.572733521840852e-16,
 2.4085904525334865e-16,
 0.0]

## Professionalism
50% Minghao Ru

50% Tong Yang


## Licensing
Copyright <2020> Minghao Ru, Tong Yang

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.